version: 0.2
env:
  variables:
    ECR_REPO_NAME: sonar
    AWS_ACCOUNT_ID: 985539772981
phases:
  install:
      runtime-versions:
        java: corretto17
  pre_build:
    commands:
      # Visualizar variaveis codebuild
      - export
      # Build the ECR image URI
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:${ENV}-${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
      # Authenticate Docker with ECR using temporary credentials
      - aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${ECR_MAIN_URI}"
  build:
    commands:
      # Build and package the project using Maven, skipping tests
     
      # Build the Docker image
      - docker build -t "${ECR_REPO_NAME}:latest" .
  post_build:
    commands:
      # Tag the Docker image with the ECR image URI
      - docker tag "${ECR_REPO_NAME}:latest" "${ECR_IMAGE_URI}"
      # Push the Docker image to the ECR repository
      - docker push "${ECR_IMAGE_URI}"
      # Generate an image definition JSON file for ECS Pipeline
      - printf '[{"name":"%s","imageUri":"%s"}]' "${ECR_REPO_NAME}" "${ECR_IMAGE_URI}" > imageDefinitionSLayerGetAdress.json
artifacts:
  base-directory: .
  files:
    - 'imageDefinitionSLayerGetAdress.json'
